//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyHeroAcademiaWPF.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Class()
        {
            this.Student = new HashSet<Student>();
        }
    
        public int IdClass { get; set; }
        public string Name { get; set; }
        public int IdRank { get; set; }
        public int IdPotential { get; set; }
        public decimal AttackPower { get; set; }
        public decimal ProtectionPower { get; set; }
        public decimal SearchPower { get; set; }
        public decimal SupportPower { get; set; }
        public decimal SupplyForce { get; set; }
    
        public virtual Potential Potential { get; set; }
        public virtual Rank Rank { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student> Student { get; set; }

        public override string ToString()
        {
            return Name;
        }
    }
}
