//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyHeroAcademiaWPF.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinalPower
    {
        public int IdFinalPower { get; set; }
        public string Name { get; set; }
        public decimal AttackPower { get; set; }
        public decimal ProtectionPower { get; set; }
        public decimal SearchPower { get; set; }
        public decimal SupportPower { get; set; }
        public decimal SupplyForce { get; set; }
        public int IdSuperpower { get; set; }
    
        public virtual Superpower Superpower { get; set; }

        public override string ToString()
        {
            return Name;
        }
    }
}
