//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyHeroAcademiaWPF.ADO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyHeroAcademiaEntities : DbContext
    {
        public MyHeroAcademiaEntities()
            : base("name=MyHeroAcademiaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Class> Class { get; set; }
        public virtual DbSet<Image> Image { get; set; }
        public virtual DbSet<Potential> Potential { get; set; }
        public virtual DbSet<PowerAcquisitionType> PowerAcquisitionType { get; set; }
        public virtual DbSet<PowerQualityType> PowerQualityType { get; set; }
        public virtual DbSet<PowerType> PowerType { get; set; }
        public virtual DbSet<Rank> Rank { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<StudentSuperpower> StudentSuperpower { get; set; }
        public virtual DbSet<Superpower> Superpower { get; set; }
        public virtual DbSet<FinalPower> FinalPower { get; set; }
    }
}
