//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyHeroAcademiaWPF.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.StudentSuperpower = new HashSet<StudentSuperpower>();
        }
    
        public int IdStudent { get; set; }
        public int IdImage { get; set; }
        public string Name { get; set; }
        public int IdClass { get; set; }
        public int IdRank { get; set; }
        public decimal AttackPower { get; set; }
        public decimal ProtectionPower { get; set; }
        public decimal SearchPower { get; set; }
        public decimal SupportPower { get; set; }
        public decimal SupplyForce { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Image Image { get; set; }
        public virtual Rank Rank { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentSuperpower> StudentSuperpower { get; set; }
    }
}
