//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyHeroAcademiaWPF.ADO
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class StudentSuperpower
    {
        public int IdStudentSuperpower { get; set; }
        public int IdStudent { get; set; }
        public int IdSuperpower { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Superpower Superpower { get; set; }

        public StudentSuperpower(int idStudentSuperpower, int idStudent, int idSuperpower)
        {
            IdStudentSuperpower = idStudentSuperpower;
            IdStudent = idStudent;
            IdSuperpower = idSuperpower;
        }


        public StudentSuperpower()
        {

        }

        public override string ToString()
        {
            return App.Connection.Superpower.Where(z => z.IdSuperpower == IdSuperpower).FirstOrDefault().Name;
        }
    }
}
