//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyHeroAcademiaWPF.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Superpower
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Superpower()
        {
            this.StudentSuperpower = new HashSet<StudentSuperpower>();
            this.FinalPower = new HashSet<FinalPower>();
        }
    
        public int IdSuperpower { get; set; }
        public string Name { get; set; }
        public int IdPowerType { get; set; }
        public decimal AttackPower { get; set; }
        public decimal ProtectionPower { get; set; }
        public decimal SearchPower { get; set; }
        public decimal SupportPower { get; set; }
        public decimal SupplyForce { get; set; }
        public int IdRank { get; set; }
        public int IdPowerQualityType { get; set; }
        public int IdPowerAcquisitionType { get; set; }
    
        public virtual PowerAcquisitionType PowerAcquisitionType { get; set; }
        public virtual PowerQualityType PowerQualityType { get; set; }
        public virtual PowerType PowerType { get; set; }
        public virtual Rank Rank { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentSuperpower> StudentSuperpower { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FinalPower> FinalPower { get; set; }

        public override string ToString()
        {
            return Name;
        }
    }
}
